config/routes.rb
Todo::Application.routes.draw do
  root :to => 'tasks#jindex'
  match 'session/register' => 'session#register'
  match 'session/create' => 'session#create'
  match 'session/login' => 'session#login'
  match 'session/logout' => 'session#logout'
  resources :users
  resources :tasks do
    member do
      put 'close'
    end
    collection do
      get 'jindex'
    end  
  end    
  scope "api" do 
    resources :items
  end
  match 'public/' => 'public#index'
  match '/sms' => 'public#sms', :via => [:get, :post]
  match '/email' => 'public#email', :via => [:get, :post]
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  scope :open, where(:status => 'Open')
  scope :pending, where(:status => 'Pending')
  scope :closed, where(:status => 'Closed')
  scope :active, where("status != 'Closed'")
  scope :any # all returns an array, any will return an ActiveRelation
  
  default_scope where(:active => 1).order("created_at DESC")
  
  self.per_page = 10
    
  class << self
    def select_status
      ['Open', 'Pending', 'Closed']
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate
  before_filter :scope_task_to_user_lists, :except => [:index, :new, :create] 
  
  def index
    @show = params[:show] || 'active'
    if @show and @show[/any|open|pending|closed|active/i]
      @tasks = Task.send(@show.to_sym).paginate(:page => params[:page])
    else  
     @tasks = Task.active.paginate(:page => params[:page])
    end
    @task = current_user.tasks.build
    @task.status = 'Open'
  end
  
  def show

  end

  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit

  end

  # POST /tasks
  def create
    @task = Task.new(params[:task])
    if @task.save
      flash.now[:notice] = 'Task was successfully created.'
      respond_to do |format|
        format.html { redirect_to action: "index" }
        format.js
      end
       
    else
      render action: "new"
    end
  end

  # PUT /tasks/1
  def update
    if @task.update_attributes(params[:task])
      flash[:notice] = 'Task was successfully updated.'
      redirect_to action: :index
    else
      render action: "edit" 
    end
  end
  
  # PUT /tasks/1/close
  def close    
    # format this for AJAX 
    if @task.update_attributes(:status => "Closed")
      respond_to do |format|
        format.html { redirect_to action: "index", show: params[:show] }
        format.js 
      end  
    else
      render action: "index" 
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.active = 0
    @task.save
    redirect_to tasks_url
  end

private
  def scope_task_to_user_lists
    # right now the tasks are not scoped to any list, basically there is only one list
    # but it will be important to fix this once multiple lists are available
    @task = Task.find(params[:id]) if params[:id]
  end  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Task</legend>
		<% if @task.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

	      <ul>
	      <% @task.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
    <div class="control-group">
      <%= f.label :user_id, :class => 'control-label' %>
      <div class="controls">
				<%= f.select :user_id, User.select_user, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
				<%= f.select :status, Task.select_status, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area span8' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', tasks_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/tasks/_inline_form.html.erb
<%= form_for(@task, :remote => true, :html => {:id => "task_form", :class => "well form-inline"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :user_id %>
  <%= f.hidden_field :status %>
	
  <%= f.text_field :description, :id => "new_task_description", :class => "span10" %>
	<%= f.submit "Add Task", :id => "new_task", :class => "btn-primary" %>
  
	
<% end %>

app/views/tasks/_task_row.html.erb
<tr <%= "id=task_#{task.id} class='#{cycle 'odd', 'even'} #{html_class}'" %> >
  <td><%= link_to task.user.display_name, task.user %></td>
  <td><%= task.status %></td>
  <td><%= link_to truncate(task.description,:length => 75), edit_task_path(task) %></td>
  <td>
    <%= link_to 'Edit', edit_task_path(task), :class => 'btn btn-mini' %>
    <%= link_to 'Close', close_task_path(task), :method => :put, :class => 'btn btn-mini btn-success', :remote => true %>
  </td>
</tr>

app/views/tasks/close.js.erb
$('#tasks <%="tr#task_#{@task.id}" %>').fadeOut(400).remove();

$('#tasks tr.row:odd').animate({'backgroundColor' : '#DDE'}, 500);
$('#tasks tr.row:even').animate({'backgroundColor' : '#EEF'}, 500);

app/views/tasks/create.js.erb
// alert("hi mom");


// $('#tasks').prepend('<%#= escape_javascript(render(@task)) %>');

$('#tasks tr:first').after("<%= escape_javascript(render(:partial => 'task_row', :locals => {:task => @task, :html_class => 'new'})) %>");
$('#tasks tr.new').animate({'backgroundColor' : '#D9EDF7'}, 700).delay(100).animate({'backgroundColor' : '#FFF'}, 700);
$('#task_form')[0].reset();
$('#tasks tr').removeClass('new');

// $('#tasks tr.row:odd').animate({'backgroundColor' : '#DDE'}, 500);
// $('#tasks tr.row:even').animate({'backgroundColor' : '#EEF'}, 500);

app/views/tasks/edit.html.erb
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<div id="filter-form" class="span11">
	<h3 class="pull-left">Sort by:&nbsp;</h3>
	<div class="btn-group">
		<%= link_to 'Any', tasks_path(:show => 'any'), :class => "btn #{'btn-inverse' if @show == 'any'}" %>
		<%= link_to 'Active', tasks_path(:show => 'active'), :class => "btn #{'btn-inverse' if @show == 'active'}" %>
		<%= link_to 'Open', tasks_path(:show => 'open'), :class => "btn #{'btn-inverse' if @show == 'open'}" %>
		<%= link_to 'Pending', tasks_path(:show => 'pending'), :class => "btn #{'btn-inverse' if @show == 'pending'}" %>
		<%= link_to 'Closed', tasks_path(:show => 'closed'), :class => "btn #{'btn-inverse' if @show == 'closed'}" %>
	</div>	
</div>

<table id="tasks" class="table table-striped">
  <thead>
    <tr>
      <th>Submitted by</th>
      <th>Status</th>
      <th class='wide'>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
		<%= render :partial => "task_row", :collection => @tasks, :as => :task, :locals => {:html_class => ''} %>
  </tbody>
</table>

<%= render :partial => 'inline_form' %>

<%= will_paginate @tasks %>

app/views/tasks/jindex.html.erb
<%= content_tag "div", :id => "items", :data => {tasks: @tasks} do %>
	Loading...
<% end -%>	

app/views/tasks/new.html.erb
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<h1>/Task</h1>

<p>
  <b>User</b><br>
  <%= @task.user_id %>
</p>

<p>
  <b>Assigned</b><br>
  <%= @task.assigned %>
</p>

<p>
  <b>Status</b><br>
  <%= @task.status %>
</p>

<p>
  <b>Description</b><br>
  <%= @task.description %>
</p>

<p>
  <b>Finished at</b><br>
  <%= @task.finished_at %>
</p>

<p>
  <b>Active</b><br>
  <%= @task.active %>
</p>

<div class="form-actions">
  <%= link_to 'Back', tasks_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_task_path(@task), :class => 'btn' %>
  <%= link_to 'Delete', task_path(@task), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>