config/routes.rb
Todo::Application.routes.draw do
  root :to => 'tasks#jindex'
  match 'session/register' => 'session#register'
  match 'session/create' => 'session#create'
  match 'session/login' => 'session#login'
  match 'session/logout' => 'session#logout'
  resources :users
  resources :tasks do
    member do
      put 'close'
    end
    collection do
      get 'jindex'
    end  
  end    
  scope "api" do 
    resources :items
  end
  match 'public/' => 'public#index'
  match '/sms' => 'public#sms', :via => [:get, :post]
  match '/email' => 'public#email', :via => [:get, :post]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :tasks
  has_many :items
  default_scope where(:active => 1)
  
  
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  # validates :email, :uniqueness => true 
  validates :sms_number, :format => { :with => /^\+.[0-9]{9,10}$/i, :on => :create, :message => "Phone Number is invalid"}
  validates :password, :presence => true, :on => :create
  
  def display_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    elsif email == "unknown@sample.com"
      sms_number
    else
      email  
    end  
  end
  
  def create_task(body)
    if body[/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i]
      # if the total content of the task is an email address, update the users email address
      self.email = body
      self.save
    else
      task = self.tasks.new({:status => "Open", :description => body}) 
      task.save 
    end
  end
  
  class << self
    def select_user
      self.all.map {|u| [u.display_name, u.id] }
    end
    
    def find_or_create_by_sms_number(number)
      Rails.logger.debug "User.find_or_create_by_sms(#{number})"
      creator = self.find_by_sms_number(number) || User.new({:sms_number => number, :password => 'leclerk', :email => "unknown@sample.com"})
      if creator.save
        Rails.logger.info "creator.save"
        creator
      else
        creator.errors.full_messages.each do |msg|
          Rails.logger.warn msg
        end  
        User.first
      end 
      rescue
        Rails.logger.error "RESCUE in find_or_create_by_sms_number(#{number})" 
        User.first 
    end
    
    def find_or_create_by_email(from)
      Rails.logger.debug "User.find_or_create_by_email(#{from})"
      email = from[/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i]
      creator = self.find_by_email(email) || User.new({:email => email, :password => 'leclerk', :sms_number => "+12145555555"})
      if creator.save
        Rails.logger.debug "creator.save"
        creator
      else
        creator.errors.full_messages.each do |msg|
          Rails.logger.warn msg
        end  
        User.first
      end 
      rescue
        Rails.logger.error "RESCUE in find_or_create_by_email(#{from})" 
        User.first 
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate

  def index
    @users = User.unscoped.all
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.active = 0
    @user.save
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Phone Number +12145555555' %><br />
    <%= f.text_field :sms_number %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'All Users', users_path %> |
<%= link_to 'Tasks', tasks_path  %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Sms number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.sms_number %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="user">
	<p>
	  <b>First:</b>
	  <%= @user.first_name %>
	</p>
	<p>
	  <b>Last:</b>
	  <%= @user.last_name %>
	</p>
	<p>
	  <b>Email:</b>
	  <%= @user.email %>
	</p>

	<p>
	  <b>Phone Number:</b>
	  <%= @user.sms_number %>
	</p>
</div>
	
<div id="links">
	<%= link_to 'Edit profile', edit_user_path(@user) %> | 
	<%= link_to 'Tasks', tasks_path %>
</div>	