config/routes.rb
Todo::Application.routes.draw do
  root :to => 'tasks#jindex'
  match 'session/register' => 'session#register'
  match 'session/create' => 'session#create'
  match 'session/login' => 'session#login'
  match 'session/logout' => 'session#logout'
  resources :users
  resources :tasks do
    member do
      put 'close'
    end
    collection do
      get 'jindex'
    end  
  end    
  scope "api" do 
    resources :items
  end
  match 'public/' => 'public#index'
  match '/sms' => 'public#sms', :via => [:get, :post]
  match '/email' => 'public#email', :via => [:get, :post]
  

end

app/views/layouts/_error.html.erb
<a class="close" data-dismiss="alert">×</a>
<h4 class="alert-heading">An Error Occurred</h4>
<%= error.html_safe %>

app/views/layouts/_footer.html.erb
<div class="pull-right">
	<h4>Little Elm</h4>
</div>

app/views/layouts/_header.html.erb
<div id="header" class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">To Do's</a>
			<div class="non-responsive">
				<% if current_user %>
					<ul id="nav" class="non-nav">
						<li><%= link_to 'Tasks', tasks_path, :class => (current_page?(:controller => :tasks ) ? 'current' : '') %></li>
						<li><%= link_to 'Users', users_path, :class => (current_page?(:controller => :users ) ? 'current' : '') %></li>
						<li><%= link_to 'Log Out', session_logout_path, :class => 'pull-right' %></li>
					</ul>
				<% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notice.html.erb
<h3 class="notice"><%= notice %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container">
		<div id="header" class="row">
			<div class="span12">
				<%= render 'layouts/header' %>
			</div>	
		</div>	
		<div id="flash_error" class=" row">
			<% if flash[:error]%>
				<div class="container span11 alert alert-error">	
					<%= (render 'layouts/error', {:error => flash[:error]}) %>	
				</div>
			<% end -%>	
			<% if flash[:notice]%>	
				<div class="span9 offset1 alert alert-info ">
					<a class="close" data-dismiss="alert">×</a>	
					<%= (render 'layouts/notice', {:notice => flash[:notice]}) %>
				</div>
			<% end -%>
		</div>
		<div id="main"  class="row">
			<div class="span12">
				<%= yield %>
			</div>	
		</div>
		<div class="clear"></div>			
		<div id="footer" class="row">
			<div class="span12">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</div>
</body>
</html>